
pool: hosted-linux

pr: none

trigger:
  branches:
    include:
      - master
  paths:
    include:
      - src/Ip.Website
      - pipelines/website.yaml


parameters:

- name: projectPath
  type: string
  default: src/Ip.Website

- name: projectName
  type: string
  default: Ip.Website

- name: destDirectory
  type: string 
  default: /var/www/ip

- name: url
  type: string
  default: http://localhost:5075
  
- name: service
  type: object
  default:
    description: Internet Protocol
    identifier: ip
    name: kestrel-ip
